// Generated by scripts/generate-protect-config.mjs.
// Commit this file, but do not commit .protect.local.json.
export const protectPasswordHash = "5a2a7f6f371cf50a9c5dc063d3cd9de69ad7fef720bbafd69d39b3da09ccf37b"
export const protectPasswordSalt = "62fd6976c7fa09aa53d46688620a7ce2"
export const protectPasswordLength = 6
export const protectKdfIterations = 150000
